# Generated by Django 3.1 on 2021-01-26 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210126_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationdetailimages',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.organization'),
        ),
    ]
