# Generated by Django 3.1 on 2021-01-26 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210126_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='blog.organization'),
        ),
    ]
