# Generated by Django 3.1 on 2021-01-27 13:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_auto_20210126_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='budget',
            field=models.PositiveIntegerField(help_text='на одного человека в сомах'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='organization',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, default=2021),
        ),
        migrations.AlterField(
            model_name='organizationdetailimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='org_detail_img/'),
        ),
        migrations.AlterField(
            model_name='organizationdetailimages',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='blog.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'organization')},
                'index_together': {('user', 'organization')},
            },
        ),
    ]
