# Generated by Django 3.1 on 2021-01-28 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210127_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewDetailImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='review_detail_img/')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.review')),
            ],
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
