# Generated by Django 3.1 on 2021-01-28 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210128_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewdetailimages',
            name='title',
        ),
    ]
